id: rds-public-endpoint

info:
  name: RDS check for Public Endpoint
  author: jlgore
  severity: critical
  description: |
    Verifies that AWS RDS instances are not allowed to have public endpoints.
  reference:
    - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.WorkingWithRDSInstanceinaVPC.html
  tags: cloud,devops,aws,amazon,rds,aws-cloud-config

flow: |
  code(1)
  code(2)
  for(let rdsInstance of iterate(template.databases)){
    set("database", rdsInstance)
    code(3)
  }
  code(4)

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: |
      pulumi up --yes
  
  - engine:
      - sh
      - bash
    source: |
      aws rds describe-db-instances --query 'DBInstances[*].DBInstanceIdentifier'

    extractors:
      - type: json # type of the extractor
        internal: true
        name: databases
        json:
          - '.[]'

  - engine:
      - sh
      - bash
    source: |
        aws rds describe-db-instances --db-instance-identifier $database --query 'DBInstances[0].[PubliclyAccessible]'
    matchers:
      - type: word
        words:
          - 'true'

    extractors:
      - type: dsl
        dsl:
          - '"The RDS instance " + database +" is publicly accessible."'
    
  - engine:
      - sh
      - bash
    source: |
        pulumi destory --yes
# digest: 490a00463044022031d7572bb548ac4b8d7b39c34bacf9871ac4a1843279b9a12e50d9b7e3af49130220236d7e9f691980f1f9aacd17cea141c713f33c463d0b2862195111ac9f752af3:cd133dde9da4140ddc0faa5479e857d8